import React, { useState } from 'react';
import { useTrading } from '../../context/TradingContext';
import { Button } from '../common/Button';
import { ShieldCheck, Mail, Lock, Smartphone, ArrowRight, KeyRound } from 'lucide-react';

export const AuthView: React.FC = () => {
  const { setCurrentView, showToast, setIsAuthModalOpen } = useTrading();
  const [authMode, setAuthMode] = useState<'signin' | 'signup' | 'otp'>('signin');
  const [email, setEmail] = useState('trader@tradeon.io');
  const [password, setPassword] = useState('••••••••••••');
  const [otp, setOtp] = useState(['4', '8', '2', '9', '1', '0']);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (authMode === 'signin') {
      // Prompt 2FA OTP verification
      setAuthMode('otp');
      showToast('OTP Code Sent', 'Enter the 6-digit verification code sent to your device.', 'info');
      return;
    }

    // Complete authentication
    showToast('Authenticated', 'Welcome to Tradeon Trading Terminal.', 'success');
    setIsAuthModalOpen(false);
    setCurrentView('app-dashboard');
  };

  return (
    <div className="w-full max-w-md mx-auto p-1 text-[#181A20] select-none">
      <div className="text-center space-y-1 mb-5">
        <div className="w-9 h-9 rounded-[4px] bg-[#F0B90B] text-[#181A20] font-black flex items-center justify-center text-[16px] mx-auto mb-2 shadow-xs">
          T
        </div>
        <h2 className="text-[20px] font-bold text-[#181A20] tracking-tight">
          {authMode === 'signup'
            ? 'Open Tradeon Account'
            : authMode === 'otp'
            ? 'Two-Factor Authentication'
            : 'Sign in to Tradeon Terminal'}
        </h2>
        <p className="text-[12px] text-[#707A8A]">
          {authMode === 'otp'
            ? 'Enter the 6-digit security code generated by your authenticator app.'
            : 'Access real-time order books, live depth, and segregated ledger balances.'}
        </p>
      </div>

      {/* Mode Switcher Tabs */}
      {authMode !== 'otp' && (
        <div className="grid grid-cols-2 p-1 bg-[#F5F6F8] border border-[#DFE2E6] rounded-[4px] mb-4">
          <button
            type="button"
            onClick={() => setAuthMode('signin')}
            className={`py-1.5 text-[12px] font-semibold rounded-[3px] transition-colors cursor-pointer ${
              authMode === 'signin' ? 'bg-white text-[#181A20] font-bold shadow-xs' : 'text-[#707A8A]'
            }`}
          >
            Sign In
          </button>
          <button
            type="button"
            onClick={() => setAuthMode('signup')}
            className={`py-1.5 text-[12px] font-semibold rounded-[3px] transition-colors cursor-pointer ${
              authMode === 'signup' ? 'bg-white text-[#181A20] font-bold shadow-xs' : 'text-[#707A8A]'
            }`}
          >
            Register
          </button>
        </div>
      )}

      {authMode === 'otp' ? (
        /* OTP 6-Digit Screen */
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex justify-center gap-2 my-4">
            {otp.map((digit, idx) => (
              <input
                key={idx}
                type="text"
                maxLength={1}
                value={digit}
                onChange={(e) => {
                  const newOtp = [...otp];
                  newOtp[idx] = e.target.value;
                  setOtp(newOtp);
                }}
                className="w-10 h-12 text-center text-[18px] font-bold font-mono bg-[#F5F6F8] border border-[#DFE2E6] focus:border-[#F0B90B] focus:bg-white rounded-[4px] text-[#181A20] focus:outline-none"
              />
            ))}
          </div>

          <Button fullWidth size="md" variant="primary" type="submit" className="font-bold cursor-pointer">
            Verify & Enter Terminal
          </Button>

          <button
            type="button"
            onClick={() => setAuthMode('signin')}
            className="w-full text-center text-[12px] text-[#707A8A] hover:text-[#181A20] cursor-pointer"
          >
            Back to Password Login
          </button>
        </form>
      ) : (
        /* Credentials Form */
        <form onSubmit={handleSubmit} className="space-y-3 text-[12px]">
          <div>
            <label className="block font-medium text-[#707A8A] mb-1">Email Address</label>
            <div className="relative">
              <Mail className="w-4 h-4 absolute left-3 top-2.5 text-[#707A8A]" />
              <input
                type="text"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full h-9 pl-9 pr-3 rounded-[4px] bg-[#F5F6F8] border border-[#DFE2E6] text-[#181A20] focus:border-[#F0B90B] focus:bg-white focus:outline-none"
              />
            </div>
          </div>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="font-medium text-[#707A8A]">Password</label>
              {authMode === 'signin' && (
                <button
                  type="button"
                  onClick={() => showToast('Password Reset', 'Reset link sent to registered email.', 'info')}
                  className="text-[11px] text-[#946800] hover:underline cursor-pointer"
                >
                  Forgot?
                </button>
              )}
            </div>
            <div className="relative">
              <Lock className="w-4 h-4 absolute left-3 top-2.5 text-[#707A8A]" />
              <input
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full h-9 pl-9 pr-3 rounded-[4px] bg-[#F5F6F8] border border-[#DFE2E6] text-[#181A20] focus:border-[#F0B90B] focus:bg-white focus:outline-none"
              />
            </div>
          </div>

          <Button fullWidth size="md" variant="primary" type="submit" className="font-bold mt-2 cursor-pointer">
            <span>{authMode === 'signup' ? 'Create Account' : 'Sign In'}</span>
            <ArrowRight className="w-4 h-4 ml-1.5" />
          </Button>

          <div className="pt-3 text-center text-[11px] text-[#707A8A]">
            Protected by Tradeon 256-bit institutional authentication security.
          </div>
        </form>
      )}
    </div>
  );
};

export default AuthView;
